# Generated by Django 5.1.1 on 2024-09-27 10:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в: ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено в: ')),
                ('title', models.CharField(max_length=120, verbose_name='Название департамента')),
                ('slug', models.CharField(blank=True, max_length=120, unique=True, verbose_name='Альт.название')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в: ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено в: ')),
                ('number', models.IntegerField(verbose_name='Номер документа')),
                ('name', models.CharField(max_length=120, verbose_name='Наименование документа')),
                ('document', models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx', 'doc', 'pdf'])], verbose_name='Документ')),
                ('departament', models.ForeignKey(db_column='departament', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_of_departament', to='document.departament')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'db_table': 'documents',
            },
        ),
    ]
