# Generated by Django 5.1.1 on 2024-09-27 10:37

import django.core.validators
import document.services.path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to=document.services.path.path_document, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx', 'doc', 'pdf'])], verbose_name='Документ'),
        ),
    ]
